### ISSUE TITLE
Building behind web proxies

### ISSUE THREAD

**Issue by jasonheffner** [espocrm/docker#1]
Thanks for the official Docker repository.  I wrap all our gitlab CI/CD around this repo as a git submodule. The only issue I ran into was the use of git:// when cloning php-zmq in the Docker build script when running behind a web proxy. I was able to get around this by replacing git:// with https:// in the deployment script after checkout.

**Comment by tmachyshyn** [comment]
Thanks for your comment. Done, https://github.com/espocrm/docker/commit/23895652d8b465969480c40c2842ea6c0d223c5d#diff-b2875299404acb0984502587dcbdad13.
