### ISSUE TITLE
Is this website a joke?

### ISSUE THREAD

**Issue by TheBotlyNoob** [espocrm/docker#3]
Is [this](http://ophabinap.ddns.net/forum/?q=%20) website a joke? As it seems to be hosted by you

**Comment by tmachyshyn** [comment]
We have to inform you that EspoCRM’s logo is used for illegal purposes. We neither own this domain nor manage this server. We are not administrators of this site as well. These are the reasons why we cannot disable the website and remove the infringing materials.

**Comment by jurkov** [comment]
This is a phishing attempt i think ;-)

**Comment by TheBotlyNoob** [comment]
I think thats a given...
