### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by jasonheffner** [espocrm/docker#8]
EspoCRM 6.1.10, and 6.1.9

LDAP authentication not working in Docker Hub image. LDAP Authentication working fine when I build using...

docker-compose.yml

    image: crm-webapp:${espo_version}
    build:
      context: ./docker/apache
      dockerfile: Dockerfile

CI job

    - cd ./docker/apache
    - docker build --no-cache -t crm-webapp:${espo_version} -f Dockerfile .

Ldap authentication has been working for multiple versions. I wanted to switch to Docker Hub image. When trying to use docker hub image authentication will not work. I can easily swap in/out docker hub image and going from working to not working and vice versa. Here was the image I tried...

docker-compose.yml

    image: espocrm/espocrm:6.1.10-apache

I'm not sure what the differences are/or if you are missing ldap libraries in the docker hub version.

**Comment by jasonheffner** [comment]
more info: I use port 389 over TLS for ldap authentication with a user login filter

**Comment by jasonheffner** [comment]
This one has me stumped .. updated and tested with espocrm/espocrm:7-apache .. I'm not sure the difference in the docker-compose build vs buildkit dockerhub image.

**Comment by jasonheffner** [comment]
Hi,

I attached a screenshot. The error message from the DEBUG log was 

ERROR: LDAP: Could not connect to LDAP server [XXXXXXXXXX], details: 0x5b (Connect error; (unknown error code)): XXXXXXXXXX:389 [] []

In case there was a compatibility problem I also updated docker and docker-compose on the host server. If I docker-compose build the resulting image works fine. If I use the one from docker hub it can't connect to ldap.

![ldap_settings](https://user-images.githubusercontent.com/867875/136637738-ff16c6e4-342b-445d-b437-cdf92948f469.jpg)

**Comment by Mexonizator** [comment]
It seems you have the same problem as me. The docker hub image has some problems with establishing a secure connection (or perhaps with locating the CA cert). 

When you try connecting using an encryption, it can't locate the CA cert, hence the error. If you try an unsecure connection, most like it'll succeed...

**Comment by jasonheffner** [comment]
I'm still going through the bullseye updates needed for the default image switch in the php:7.4-apache image. A quick fix is to use php:7.4-apache-buster for now in your docker hub images. The first hurdle was referenced here ...

https://github.com/docker-library/php/issues/1194

and solved by adding libldap-common. This alone didn't fix the TLS issue yet in the new docker hub images.
